name: Run integration tests
on:
  push:
    branches:
      - acceptance
      - development

env:
  CI: true
  NEXT_PUBLIC_API_URL: http://localhost:4000

jobs:
  playwright:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Set development API URL
        if: ${{ github.ref != 'refs/heads/acceptance' }}
        run: echo "PROXY_URL=https://api.diks.dev.lightbase.nl" >> $GITHUB_ENV
      - name: Set acceptance API URL
        if: ${{ github.ref == 'refs/heads/acceptance' }}
        run: echo "PROXY_URL=https://api.diks.acc.lightbase.nl" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright
        run: yarn playwright install --with-deps
      - name: Build
        run: yarn proxy & yarn build
      - name: Run tests
        run: yarn test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: test-results
