name: lint-test
on: [pull_request]

jobs:
  lint-build-test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install, Format, Check
        run: |
          yarn
          yarn format
      - name: Test, Build
        run: |
          yarn test
          yarn build
