name: PR checks
on: [pull_request]

env:
  CI: true

jobs:
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Run format
        run: |
          yarn install
          yarn format

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Run test
        run: |
          yarn install
          yarn test --passWithNoTests

  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: next-build-cache-${{ hashFiles('./yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            next-build-cache-${{ hashFiles('./yarn.lock') }}-

      - name: Run build
        run: |
          yarn
          yarn build

  e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          path: "./frontend"

      - uses: actions/checkout@v4
        with:
          repository: "lightbasenl/platform-backend-template"
          token: ${{ secrets.SCAFFOLD_BACKEND_TOKEN }}
          path: "./backend"

      - name: Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/frontend/.next/cache
          key:
            next-build-cache-${{ hashFiles('./frontend/yarn.lock') }}-${{ hashFiles('./frontend/**.[jt]s',
            './frontend/**.[jt]sx') }}
          restore-keys: |
            next-build-cache-${{ hashFiles('./frontend/yarn.lock') }}-

      - name: Install
        run: |
          cd ./backend
          yarn
          yarn compas generate application --skip-lint
          cd ../frontend
          yarn
          yarn playwright install --with-deps chromium

      - name: Run e2e
        env:
          TENANT_ORIGIN: "scaffold.acc.lightbase.nl"
          TENANT_API_URL: "http://localhost:3001"
        run: |
          cd ./frontend
          yarn test:e2e:ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: ./frontend/test-results
