name: PR checks
on: [pull_request]

env:
  CI: true

jobs:
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run format

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test --passWithNoTests

  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key:
            next-build-cache-${{ hashFiles('./package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            next-build-cache-${{ hashFiles('./package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

  e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          path: "./frontend"

      - uses: actions/checkout@v4
        with:
          repository: "lightbasenl/platform-backend-template"
          token: ${{ secrets.SCAFFOLD_BACKEND_TOKEN }}
          path: "./backend"

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/frontend/.next/cache
          key:
            next-build-cache-${{ hashFiles('./frontend/package-lock.json') }}-${{
            hashFiles('./frontend/**.[jt]s', './frontend/**.[jt]sx') }}
          restore-keys: |
            next-build-cache-${{ hashFiles('./frontend/package-lock.json') }}-

      - name: Install
        run: |
          cd ./backend
          npm install
          npx compas generate application --skip-lint
          cd ../frontend
          npm install
          npx playwright install --with-deps chromium

      - name: Run e2e
        env:
          TENANT_ORIGIN: "scaffold.acc.lightbase.nl"
          TENANT_API_URL: "http://localhost:3001"
        run: |
          cd ./frontend
          npm run test:e2e:ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: ./frontend/test-results
